import os
import json
import requests
import praw
from pytrends.request import TrendReq
from datetime import datetime

# ================= 1. 获取环境配置 =================
REDDIT_ID = os.environ.get("REDDIT_CLIENT_ID")
REDDIT_SECRET = os.environ.get("REDDIT_SECRET")
MINIMAX_KEY = os.environ.get("MINIMAX_API_KEY")
MINIMAX_GROUP_ID = os.environ.get("MINIMAX_GROUP_ID")

# ================= 2. 抓取数据 =================
def get_data():
    data_summary = {"date": datetime.now().strftime("%Y-%m-%d"), "trends": []}
    
    # --- Reddit ---
    try:
        if REDDIT_ID and REDDIT_SECRET:
            reddit = praw.Reddit(client_id=REDDIT_ID, client_secret=REDDIT_SECRET, user_agent='news_bot/1.0')
            posts = []
            for sub in ["news", "popular"]:
                for post in reddit.subreddit(sub).hot(limit=5):
                    posts.append(f"[{sub}] {post.title} (Score: {post.score})")
            data_summary["reddit"] = posts
        else:
            data_summary["reddit"] = ["未配置 Reddit API，跳过抓取"]
    except Exception as e:
        data_summary["reddit"] = [f"抓取出错: {str(e)}"]

    # --- Google Trends ---
    try:
        pytrends = TrendReq(hl='en-US', tz=360)
        trends = pytrends.trending_searches(pn='united_states').head(10)[0].tolist()
        data_summary["google"] = trends
    except Exception as e:
        data_summary["google"] = [f"抓取出错: {str(e)}"]

    return data_summary

# ================= 3. 调用 Minimax AI =================
def analyze_with_minimax(data):
    if not MINIMAX_KEY or not MINIMAX_GROUP_ID:
        return "❌ 错误：未配置 Minimax API Key，无法生成分析。请查看 raw_data.json 手动分析。"

    url = f"https://api.minimax.chat/v1/text/chatcompletion_pro?GroupId={MINIMAX_GROUP_ID}"
    headers = {"Authorization": f"Bearer {MINIMAX_KEY}", "Content-Type": "application/json"}
    
    prompt = f"""
    你是一个美国新闻分析师。今天是 {data['date']}。
    请根据以下采集到的 Google 热搜和 Reddit 热帖，写一份《美国今日热点简报》。
    要求：
    1. 找出最热门的3-5个事件。
    2. 用中文总结，每个事件包含【事件概述】和【舆论反应】。
    3. 忽略无关的广告或无意义内容。
    
    数据如下：
    Google热搜: {json.dumps(data['google'], ensure_ascii=False)}
    Reddit讨论: {json.dumps(data['reddit'], ensure_ascii=False)}
    """

    payload = {
        "model": "abab5.5-chat", # 如果你有abab6.5权限可修改此处
        "messages": [{"sender_type": "USER", "sender_name": "用户", "text": prompt}],
        "reply_constraints": {"sender_type": "BOT", "sender_name": "AI助手"},
        "bot_setting": [{"bot_name": "AI助手", "content": "你是一个分析师"}]
    }
    
    try:
        res = requests.post(url, headers=headers, json=payload).json()
        return res['reply']
    except Exception as e:
        return f"AI 调用失败: {str(e)}"

# ================= 主程序 =================
if __name__ == "__main__":
    print("开始抓取...")
    data = get_data()
    
    # 保存原始数据备份
    with open("raw_data.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print("开始AI分析...")
    report = analyze_with_minimax(data)
    
    # 将报告写入 Markdown 文件
    with open("DAILY_REPORT.md", "w", encoding="utf-8") as f:
        f.write(f"# 🇺🇸 美国热点日报 ({data['date']})\n\n")
        f.write(report)
        f.write("\n\n---\n*Report generated by GitHub Actions*")
    
    print("完成！请查看 DAILY_REPORT.md")
